version: '2'
services:
  mysql:
    container_name: vibrato_mysql
    restart: always
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'MySuperSecurePassword'
    volumes:
      - mysqlvarlib:/var/lib/mysql
      - .:/data
    command: --init-file /data/mysql/mysql-initial.sql
    networks:
      vpcbr:
        ipv4_address: 10.1.1.200

  web:
    container_name: vibrato_web
    restart: always
    build: .
    ports:
      - "80:80"
      - "443:443"

volumes:
  mysqlvarlib:

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.1.1.0/24
         gateway: 10.1.1.1
